// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkSLodM3DsMuxwLAt5WN1uDb4DXcHSuhY',
    appId: '1:674287061302:web:f3bc5480716568f4da8b97',
    messagingSenderId: '674287061302',
    projectId: 'quizdata-63d04',
    authDomain: 'quizdata-63d04.firebaseapp.com',
    storageBucket: 'quizdata-63d04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtQFugvrbRhstM2L9hwC1Pzok1Mdx-588',
    appId: '1:674287061302:android:82b9826456c6565fda8b97',
    messagingSenderId: '674287061302',
    projectId: 'quizdata-63d04',
    storageBucket: 'quizdata-63d04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC19450yfDSC1pOIgHVDwGyf0eVqMQX1Og',
    appId: '1:674287061302:ios:6cbc25a836d73d3ada8b97',
    messagingSenderId: '674287061302',
    projectId: 'quizdata-63d04',
    storageBucket: 'quizdata-63d04.firebasestorage.app',
    iosBundleId: 'com.example.mainProject3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC19450yfDSC1pOIgHVDwGyf0eVqMQX1Og',
    appId: '1:674287061302:ios:6cbc25a836d73d3ada8b97',
    messagingSenderId: '674287061302',
    projectId: 'quizdata-63d04',
    storageBucket: 'quizdata-63d04.firebasestorage.app',
    iosBundleId: 'com.example.mainProject3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkSLodM3DsMuxwLAt5WN1uDb4DXcHSuhY',
    appId: '1:674287061302:web:02773825cf9b7566da8b97',
    messagingSenderId: '674287061302',
    projectId: 'quizdata-63d04',
    authDomain: 'quizdata-63d04.firebaseapp.com',
    storageBucket: 'quizdata-63d04.firebasestorage.app',
  );
}
